---
gitHubLogin: "mpherman2"
gitHubToken: "/usr/local/google/home/mpherman/token"
onCallAddress:
skipPullRequest: false
gitHubOrg: "mpherman2"
gitHubRepo: "testgrid"
remoteName: "testgrid"
upstreamURLBase: "https://raw.githubusercontent.com/GoogleCloudPlatform/testgrid/master"
includedConfigPaths:
  - "cluster/canary"
targetVersion: "latest"
prefixes:
  - name: "Testgrid Canary"
    prefix: "gcr.io/k8s-testgrid/"
    repo: "https://github.com/GoogleCloudPlatform/testgrid"
    summarise: true
    consistentImages: true
